### ISSUE TITLE
2.0 To-do

### ISSUE THREAD

**Issue by JuiceyBeans** [JuiceyBeans/SlugmoPack#1]
- [ ] Bump number of lanterns from making firefly jar
- [ ] Disable ash
- [ ] Music disc spawns in dungeon chests
- [ ] Copper compass
- [ ] Mod to web music
- [ ] Remove solid mobs?
- [ ] Lunar Stone armor
- [ ] Crayfish food compat
- [ ] Harder golden carrot recipe
- [ ] Mobs with more HP
